In [64]:
import pandas as pd

In [65]:
family_df = pd.read_csv('family.csv', names=['id','orderId','commonName','scientificName','pollution','description'],sep = ',', header=None)

In [66]:
family_ref_df = pd.read_csv('families_ref.csv',sep = ',', header=0)
family_ref_df.head()

,id,orderId,suborderFilter,commonName,alternateCommonName,scientificName,lifeStageName,lifeStagePrettyName,description,expandedCharacterList,hasAudio,hasImage
0,277,3,NaN,Small Winter Stoneflies,Snowflies,Capniidae,larva,Larva,Small winter stoneflies are named for the long...,The body is small (~1/4 inch) and slender and ...,1,1
1,279,3,NaN,Green Stoneflies,Sallflies,Chloroperlidae,larva,Larva,The body is small to middle-size (1/4–3/4 inch...,The body is small to middle-size (1/4–3/4 inch...,1,0
2,281,3,NaN,"Rolled-winged Stoneflies, Needleflies, Williow...",NaN,Leuctridae,larva,Larva,This family includes 6 genera with over 40 spe...,"Body long and slender, abdomen roughly cylindr...",1,0
3,283,3,NaN,"Spring Stoneflies, Forestflies",NaN,Nemouridae,larva,Larva,There are 12 North American genera with roughl...,<u>Larvae</u> generally small (less than 12 mm...,1,0
4,285,3,NaN,Roach-like Stoneflies,Roachflies,Peltoperlidae,larva,Larva,"The body is small (1/4–1 inch), stocky, with t...","The body is small (1/4–1 inch), stocky, with t...",1,0

In [71]:
family_ref_familyid_to_sciname = {}

for index, row in family_ref_df.iterrows():
    family_id = row['id']
    scientific_name = row['scientificName']
    family_ref_familyid_to_sciname[str(family_id)] = scientific_name

In [73]:
family_ref_familyid_to_sciname

{'101': 'Planariidae',
 '104': 'Lumbriculidae',
 '107': 'Asellidae',
 '109': 'Corydalidae',
 '111': 'Sialidae',
 '113': 'Dryopidae',
 '115': 'Dytiscidae',
 '119': 'Elmidae',
 '135': 'Gyrinidae',
 '140': 'Haliplidae',
 '143': 'Hydrophilidae',
 '156': 'Athericidae',
 '158': 'Blephariceridae',
 '160': 'Ceratopogonidae',
 '1603': 'Cambaridae',
 '162': 'Chironomidae',
 '168': 'Culicidae',
 '170': 'Dixidae',
 '172': 'Empididae',
 '174': 'Ephydridae',
 '175': 'Limoniidae',
 '178': 'Muscidae',
 '18': 'Hydropsychidae',
 '180': 'Pediciidae',
 '182': 'Psychodidae',
 '184': 'Ptychopteridae',
 '186': 'Simuliidae',
 '189': 'Stratiomyidae',
 '191': 'Syrphidae',
 '193': 'Tipulidae',
 '195': 'Ameletidae',
 '197': 'Baetidae',
 '202': 'Baetiscidae',
 '204': 'Caenidae',
 '206': 'Ephemerellidae',
 '2072': 'Physidae',
 '2076': 'Planorbidae',
 '2082': 'Hydrobiidae',
 '212': 'Ephemeridae',
 '215': 'Heptageniidae',
 '2151': 'Hydrobiidae',
 '2155': 'Physidae',
 '2159': 'Planorbidae',
 '222': 'Leptohyphidae',
 '2232': 'Unknown',
 '224': 'Leptophlebiidae',
 '228': 'Metretopodidae',
 '230': 'Polymitarcyidae',
 '232': 'Potamanthidae',
 '234': 'Siphlonuridae',
 '236': 'Belostomatidae',
 '238': 'Corixidae',
 '240': 'Gerridae',
 '242': 'Naucoridae',
 '244': 'Nepidae',
 '246': 'Notonectidae',
 '248': 'Veliidae',
 '251': 'Crambidae',
 '253': 'Aeshnidae',
 '255': 'Calopterygidae',
 '257': 'Coenagrionidae',
 '261': 'Cordulegastridae',
 '263': 'Corduliidae',
 '265': 'Gomphidae',
 '268': 'Lestidae',
 '270': 'Libellulidae',
 '277': 'Capniidae',
 '279': 'Chloroperlidae',
 '281': 'Leuctridae',
 '283': 'Nemouridae',
 '285': 'Peltoperlidae',
 '287': 'Perlodidae',
 '292': 'Pteronarcyidae',
 '300': 'Apataniidae',
 '302': 'Brachycentridae',
 '305': 'Calamoceratidae',
 '306': 'Dipseudopsidae',
 '308': 'Glossosomatidae',
 '31': 'Isonychiidae',
 '310': 'Goeridae',
 '312': 'Helicopsychidae',
 '314': 'Hydroptilidae',
 '316': 'Lepidostomatidae',
 '318': 'Leptoceridae',
 '323': 'Molannidae',
 '325': 'Odontoceridae',
 '327': 'Philopotamidae',
 '33': 'Limnephilidae',
 '330': 'Phryganeidae',
 '332': 'Polycentropodidae',
 '335': 'Psychomyiidae',
 '338': 'Rhyacophilidae',
 '340': 'Sericostomatidae',
 '342': 'Thremmatidae',
 '344': 'Hydrobiidae',
 '4': 'Perlidae',
 '6': 'Taeniopterygidae',
 '65': 'Unionidae',
 '68': 'Corbiculidae',
 '70': 'Sphaeriidae',
 '728': 'Dytiscidae',
 '73': 'Limnesiidae',
 '732': 'Elmidae',
 '739': 'Gyrinidae',
 '743': 'Haliplidae',
 '745': 'Hydrophilidae',
 '747': 'Psephenidae',
 '76': 'Gammaridae',
 '78': 'Poduridae',
 '783': 'Ptilodactylidae',
 '82': 'Physidae',
 '84': 'Planorbidae',
 '92': 'Naididae',
 '96': 'Glossiphoniidae'}

In [62]:
family_df.head()

,id,orderId,commonName,scientificName,pollution,description
0,1,1,Long-toed Water Beetles,Dryopidae,NaN,"This family is relatively small, with only 5 N..."
1,2,1,Predacious Diving Beetles,Dytiscidae,NaN,This is the largest North American family of a...
2,3,1,Riffle Beetles,Elmidae,NaN,"This is a large family, including 24 genera an..."
3,4,1,Whirligig Beetles,Gyrinidae,NaN,Adult members of the family Gyrinidae are uniq...
4,5,1,Crawling Water Beetles,Haliplidae,NaN,This family includes over 70 North American sp...

In [78]:
family_sciname_to_correct_id = {}

for index, row in family_df.iterrows():
    scientific_name = row['scientificName']
    correct_id = row['id']
    family_sciname_to_correct_id[scientific_name] = str(correct_id)

In [79]:
family_sciname_to_correct_id

{'Aeshnidae': '55',
 'Ameletidae': '31',
 'Apataniidae': '72',
 'Athericidae': '14',
 'Baetidae': '32',
 'Baetiscidae': '33',
 'Belostomatidae': '45',
 'Blephariceridae': '15',
 'Brachycentridae': '73',
 'Caenidae': '34',
 'Calamoceratidae': '74',
 'Calopterygidae': '56',
 'Capniidae': '63',
 'Ceratopogonidae': '16',
 'Chironomidae': '17',
 'Chloroperlidae': '64',
 'Coenagrionidae': '57',
 'Cordulegastridae': '58',
 'Corduliidae': '59',
 'Corixidae': '46',
 'Corydalidae': '53',
 'Crambidae': '52',
 'Culicidae': '18',
 'Dipseudopsidae': '75',
 'Dixidae': '19',
 'Dryopidae': '1',
 'Dytiscidae': '7',
 'Elmidae': '8',
 'Empididae': '20',
 'Ephemerellidae': '35',
 'Ephemeridae': '36',
 'Ephydridae': '21',
 'Gerridae': '47',
 'Glossosomatidae': '76',
 'Goeridae': '77',
 'Gomphidae': '60',
 'Gyrinidae': '9',
 'Haliplidae': '10',
 'Helicopsychidae': '78',
 'Heptageniidae': '37',
 'Hydrophilidae': '11',
 'Hydropsychidae': '79',
 'Hydroptilidae': '80',
 'Isonychiidae': '38',
 'Lepidostomatidae': '81',
 'Leptoceridae': '82',
 'Leptohyphidae': '39',
 'Leptophlebiidae': '40',
 'Lestidae': '61',
 'Leuctridae': '65',
 'Libellulidae': '62',
 'Limnephilidae': '83',
 'Limoniidae': '22',
 'Metretopodidae': '41',
 'Molannidae': '84',
 'Muscidae': '23',
 'Naucoridae': '48',
 'Nemouridae': '66',
 'Nepidae': '49',
 'Notonectidae': '50',
 'Odontoceridae': '85',
 'Pediciidae': '24',
 'Peltoperlidae': '67',
 'Perlidae': '68',
 'Perlodidae': '69',
 'Philopotamidae': '86',
 'Phryganeidae': '87',
 'Polycentropodidae': '88',
 'Polymitarcyidae': '42',
 'Potamanthidae': '43',
 'Psephenidae': '12',
 'Psychodidae': '25',
 'Psychomyiidae': '89',
 'Pteronarcyidae': '70',
 'Ptilodactylidae': '13',
 'Ptychopteridae': '26',
 'Rhyacophilidae': '90',
 'Sericostomatidae': '91',
 'Sialidae': '54',
 'Simuliidae': '27',
 'Siphlonuridae': '44',
 'Stratiomyidae': '28',
 'Syrphidae': '29',
 'Taeniopterygidae': '71',
 'Thremmatidae': '92',
 'Tipulidae': '30',
 'Veliidae': '51'}

In [80]:
diag_df = pd.read_csv('family_diag_characters.csv', sep = ',', header=0)

#'relationshipTypeCode','charId','taxId','diagCharType','name','description','audio','image'

In [81]:
diag_df.head()

,taxaObjectId,name,description
0,4,Glossae Shorter Than Paraglossae,Glossae much shorter than the paraglossae.
1,4,Thoracic Gills,"Multi-branched, thread-like gills present late..."
2,6,Divergent Wing Pads,"Wingpads are not parallel with body, angled aw..."
3,6,Gills Unlike Peltoperlidae,"Unlike Peltoperlidae, gills, if present, are ..."
4,6,Hind Legs Don't Reach,"When extended, hind legs do not reach end of t..."

In [82]:
correct_ids = []
for index, row in diag_df.iterrows():
    ref_id = str(row['taxaObjectId'])
    family_name = family_ref_familyid_to_sciname[ref_id]
    correct_id = family_sciname_to_correct_id[family_name]
    correct_ids.append(correct_id)

In [83]:
correct_ids

['68',
 '68',
 '71',
 '71',
 '71',
 '71',
 '71',
 '79',
 '79',
 '79',
 '79',
 '38',
 '38',
 '83',
 '53',
 '53',
 '54',
 '54',
 '1',
 '1',
 '1',
 '1',
 '7',
 '7',
 '7',
 '7',
 '8',
 '8',
 '8',
 '8',
 '9',
 '10',
 '11',
 '11',
 '11',
 '11',
 '11',
 '14',
 '14',
 '14',
 '14',
 '14',
 '15',
 '15',
 '15',
 '16',
 '16',
 '17',
 '17',
 '18',
 '18',
 '18',
 '18',
 '19',
 '19',
 '19',
 '19',
 '19',
 '20',
 '20',
 '20',
 '20',
 '20',
 '21',
 '21',
 '21',
 '22',
 '22',
 '23',
 '23',
 '23',
 '23',
 '24',
 '24',
 '24',
 '25',
 '25',
 '25',
 '25',
 '26',
 '26',
 '26',
 '26',
 '27',
 '27',
 '27',
 '28',
 '28',
 '28',
 '28',
 '29',
 '29',
 '29',
 '30',
 '30',
 '30',
 '31',
 '31',
 '31',
 '32',
 '32',
 '33',
 '34',
 '35',
 '36',
 '36',
 '36',
 '36',
 '37',
 '37',
 '39',
 '40',
 '41',
 '41',
 '42',
 '42',
 '42',
 '42',
 '43',
 '43',
 '43',
 '44',
 '44',
 '44',
 '44',
 '45',
 '45',
 '46',
 '46',
 '46',
 '47',
 '47',
 '47',
 '47',
 '48',
 '48',
 '49',
 '49',
 '50',
 '50',
 '50',
 '50',
 '51',
 '51',
 '51',
 '52',
 '52',
 '55',
 '55',
 '55',
 '55',
 '55',
 '56',
 '56',
 '57',
 '57',
 '57',
 '58',
 '58',
 '58',
 '58',
 '58',
 '59',
 '59',
 '59',
 '59',
 '59',
 '60',
 '60',
 '61',
 '61',
 '62',
 '62',
 '62',
 '63',
 '63',
 '63',
 '63',
 '63',
 '64',
 '64',
 '64',
 '64',
 '64',
 '65',
 '65',
 '65',
 '65',
 '66',
 '66',
 '66',
 '67',
 '67',
 '67',
 '67',
 '69',
 '69',
 '69',
 '70',
 '70',
 '72',
 '72',
 '72',
 '72',
 '72',
 '72',
 '73',
 '73',
 '73',
 '73',
 '74',
 '74',
 '74',
 '74',
 '75',
 '75',
 '75',
 '75',
 '76',
 '76',
 '76',
 '76',
 '76',
 '76',
 '77',
 '77',
 '77',
 '77',
 '78',
 '80',
 '80',
 '80',
 '80',
 '80',
 '80',
 '80',
 '81',
 '82',
 '84',
 '84',
 '84',
 '84',
 '85',
 '85',
 '85',
 '85',
 '86',
 '87',
 '87',
 '87',
 '87',
 '87',
 '87',
 '87',
 '87',
 '88',
 '88',
 '88',
 '88',
 '88',
 '88',
 '89',
 '90',
 '90',
 '90',
 '90',
 '91',
 '91',
 '91',
 '91',
 '91',
 '92',
 '92',
 '7',
 '7',
 '7',
 '8',
 '8',
 '9',
 '9',
 '9',
 '10',
 '10',
 '12',
 '12',
 '13',
 '13',
 '13',
 '13',
 '13',
 '13']

In [85]:
result = pandas.DataFrame(data={"correct_id": correct_ids})
result.to_csv("correct_fam_id.csv", sep=',',index=False)